### ISSUE TITLE
Neopixel not function 

### ISSUE THREAD

**Issue by Symbyos83** [bigtreetech/BIGTREETECH-GTR-V1.0#17] opened 2020-04-18 18:23 UTC
Hi, I connected 16 neopixel leds (2 strips of 8 leds) to the 5V, PF13 and GND pins related to the neopixel on my GTR Pro v1.0. During the power-up phase, the self-test works correctly but when I start a print, they do not perform the color variation like the marlin configuration. could it be that the power pins are not enough to power 16 LEDs? why would they put the relevant pins?
The firmware is **Marlin-bugfix-2.0.x** **BTT_GTR_V1.0-Demo**
Thank you.

**Comment by TheMiguelBi** [comment] 2020-04-18 18:42
UPDATE: by turning these 16 LEDs on manually via the TFT display, the LEDs light up in the desired color (remain lit even during printing).
A 5V power supply problem can therefore be ruled out ... 🤔

**Comment by TheMiguelBi** [comment] 2020-04-18 19:16
### 🚨🚨🚨
Maybe something is better explained here: https://github.com/MarlinFirmware/Marlin/issues/17024#issuecomment-595349265
### 🚨🚨🚨

**Comment by TheMiguelBi** [comment] 2020-05-01 15:29
I believe we can close this problem! 
The neopixel work regularly by initiating prints from the onboard microSD. The problems are caused by using the Graphic display **BTT_TFT35**! it's a real disaster!! the neopixel does not work during a print, the UPS does not work .....
There is a need to fix the Display firmware to solve this (and other) problems.

**Closed** 2020-05-14 13:38 UTC
